import { formatValue } from '../../../lib/outbreak/data';
import { HorizontalBars } from './Visuals';
import MobilityMap from './MobilityMap';
import styles from './outbreak.module.css';

export function IntegratedCharts({ epi,mining,security,geometry,boundaryLevel,asOf,onSelect=()=>{},briefing=false }) {
  const affected=new Set(epi?.affected.filter(z=>z.matched).map(z=>z.location)||[]);
  const mineRows=mining?[...mining.byZone].map(([location,value])=>({location,value})).filter(r=>!epi||affected.has(r.location)).sort((a,b)=>b.value-a.value):[];
  const securityRows=security?[...security.byZone].map(([location,s])=>({location,value:s.events,detail:`${s.fatalities} reported fatalities; ${s.missingFatalities} missing estimates`})).filter(r=>!epi||affected.has(r.location)).sort((a,b)=>b.value-a.value):[];
  return <>
    {epi?<>
      {!briefing&&<div className={styles.insightCards}><article><span>Reported area-level total</span><strong>{formatValue(epi.total)}</strong><small>{epi.date} · sum of reported values, separate from national figures</small></article><article><span>Areas with reported cases</span><strong>{epi.affected.length}</strong><small>Positive cumulative totals · not a count of currently active transmission areas</small></article><article><span>Areas with paired observations</span><strong>{epi.growth.length} / {epi.zones.length}</strong><small>{epi.baseline} → {epi.date} · missing comparisons excluded</small></article></div>}
      <div className={styles.chartGrid}>
        <HorizontalBars title="Largest reported burdens" subtitle={`Cumulative cases · ${epi.date}`} rows={epi.burden} source={epi.dataset.source||epi.dataset.url} onSelect={onSelect}/>
        <HorizontalBars title="Largest seven-day changes" subtitle={`${epi.baseline} → ${epi.date} · cumulative changes, not new infections`} rows={epi.growth.map(z=>({...z,value:z.delta}))} color="#e87b42" source={epi.dataset.source||epi.dataset.url} onSelect={onSelect} valueLabel={r=>`${r.value>0?'+':''}${formatValue(r.value)}`}/>
      </div>
      {epi.provinces.length>0&&<HorizontalBars title="Burden by grouping area" subtitle="Sum of matched area records; incomplete baselines have no growth percentage" rows={epi.provinces} color="#276d82" source={`${epi.dataset.source||epi.dataset.url}; uploaded grouping field`} valueLabel={r=>`${formatValue(r.value)}${r.percent!==null?` (${r.percent>0?'+':''}${r.percent.toFixed(1)}%)`:''}`}/>}
      <p className={styles.scope}>{epi.missing} missing case values on {epi.date}; {epi.absent} previously observed areas have no record on that date. {epi.unmatched} area names unmatched to the uploaded boundaries. Reported cumulative changes can include backlogs and revisions.</p>
    </>:<div className={styles.panel}><h3>Automatic epidemiological insights</h3><p>Map a cumulative confirmed-case indicator in Data & uploads, or choose a source preset. Burden and comparable-period rankings will then be generated automatically. Operational indicators remain available below.</p></div>}
    {(mining||security)&&<div className={styles.chartGrid}>
      {mining&&<HorizontalBars title={epi?'Mining sites in affected areas':'Documented mining sites by area'} subtitle="Unique site identifiers · historical observations, not current activity" rows={mineRows} color="#148d98" unit="documented sites" source="IPIS; uploaded administrative polygons" onSelect={onSelect}/>}
      {security&&<HorizontalBars title={epi?'Security events in affected areas':'Security events by mapped area'} subtitle={`${security.start} → ${security.end} · deduplicated ACLED events`} rows={securityRows} color="#80508d" unit="reported events" source="Main-app ACLED; uploaded administrative polygons" onSelect={onSelect}/>}
    </div>}
    {epi&&(mining||security)&&<div className={styles.tableWrap}><table><caption>Operational overlap — sorted by recorded security events, then mining-site count. This is not a composite risk score.</caption><thead><tr><th>Area</th><th>Cumulative cases</th><th>7-day reported change</th><th>Documented mines</th><th>Security events</th><th>Reported fatalities</th></tr></thead><tbody>{epi.affected.filter(z=>z.matched).map(z=>({...z,mines:mining?.byZone.get(z.location)||0,security:security?.byZone.get(z.location)})).sort((a,b)=>(b.security?.events||0)-(a.security?.events||0)||b.mines-a.mines).slice(0,12).map(z=><tr key={z.location}><td><button onClick={()=>onSelect(z.location)}>{z.location}</button><span className={styles.printOnly}>{z.location}</span></td><td>{formatValue(z.value)}</td><td>{z.delta===null?'No paired data':`${z.delta>0?'+':''}${formatValue(z.delta)}`}</td><td>{mining?z.mines:'Not loaded'}</td><td>{security?z.security?.events||0:'Not loaded'}</td><td>{security?`${z.security?.fatalities||0}${z.security?.missingFatalities?' + missing estimates':''}`:'Not loaded'}</td></tr>)}</tbody></table></div>}
    {mining&&<p className={styles.scope}>{mining.matched} documented mine points matched uniquely to boundaries; {mining.issues.length} could not be assigned uniquely. Sites outside the uploaded geography are not counted inside it.</p>}
    {security&&<p className={styles.scope}>Security window: {security.start}–{security.end}. {security.records.length} valid loaded events; {security.unmatched.length} without a unique spatial match; {security.issues.length} validation issues. Fatalities are reported estimates. A date window does not establish complete event coverage.</p>}
  </>;
}
export function MobilityPanel({ layers,selected,direction,onDirection,onLayer,geometry,boundaryLevel,asOf,onSelect=()=>{},briefing=false,overlays }) {
  const directions=[...new Set(layers.map(l=>l.direction))];
  return <div className={styles.panel}>
    <h3>Population mobility</h3>
    {!layers.length?<p>No numeric Flowminder, inflow or outflow fields detected in the uploaded GeoJSON. No movement layer has been inferred.</p>:<>
      {!briefing&&<div className={styles.controls} data-print-hide="true"><label>Movement direction<select aria-label="Movement direction" value={direction} onChange={e=>onDirection(e.target.value)}><option value="outflow" disabled={!directions.includes('outflow')}>Outflow{!directions.includes('outflow')?' — not present':''}</option><option value="inflow" disabled={!directions.includes('inflow')}>Inflow{!directions.includes('inflow')?' — not present':''}</option><option value="other" disabled={!directions.includes('other')}>Other mobility indicators</option></select></label><label>Mobility measure / observation<select aria-label="Mobility measure / observation" value={selected?.id||''} onChange={e=>onLayer(e.target.value)}>{layers.filter(l=>l.direction===direction).map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label></div>}
      {selected&&<><p><strong>{selected.direction==='other'?'Mobility indicator':selected.direction==='inflow'?'Inflow':'Outflow'}</strong> · {selected.date||'Date not supplied'} ({selected.dateBasis}) · {selected.unit}</p>{selected.definition&&<p><strong>Source definition:</strong> {selected.definition.window||'Documented snapshot'}{selected.definition.origins?` · cohort origins: ${selected.definition.origins}`:''}. {selected.definition.limitation} <a href={selected.definition.documentation} target="_blank" rel="noreferrer">Methodology</a></p>}<p>Values are shown exactly as supplied. A geographic indicator does not establish origin–destination routes, traveller counts or transmission.</p>
        <MobilityMap overlays={overlays} geometry={geometry} rows={selected.records} level={boundaryLevel} boundaryLevel={boundaryLevel} kind="mobility indicator" unit={selected.unit} selected="" onSelect={onSelect} label={`${selected.direction==='other'?'Mobility':selected.direction==='inflow'?'Inflow':'Outflow'} — ${selected.label}`} asOf={asOf} source={`Uploaded GeoJSON: ${selected.id}`} focusNames={selected.records.filter(r=>r.value>0).sort((a,b)=>b.value-a.value).slice(0,12).map(r=>r.location)}/>
        <HorizontalBars title="Leading mobility indicator values" subtitle={`${selected.date||'Undated'} · ${selected.direction} · no conversion to traveller counts`} rows={[...selected.records].sort((a,b)=>(b.value??-1)-(a.value??-1))} unit={selected.unit} color="#337fb1" source={`Uploaded GeoJSON: ${selected.id}`} onSelect={onSelect}/>
      </>}
    </>}
  </div>;
}
